{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    neovim
    git
    rofi
    waybar
    wget
    firefox
    pywal
    swww
    cargo
    go
    starship
    fastfetch
    jq
    pywalfox-native
    nerd-fonts.martian-mono
    lxappearance
    zed-editor
    yazi
    pavucontrol
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
    nodejs_24
    pnpm
    pnpm-shell-completion
    wl-clipboard
    iosevka
    inotify-tools
    playerctl
    meson
    ninja
    emmet-ls
    emmet-language-server
    typescript-language-server
    unzip
    python314
    hyprcursor
    flameshot
    vesktop
    gccgo15
    gcc15
    wayland
    wayland-protocols
    libinput
    pixman
    wayland-scanner
    pkg-config
    cmake
    xorg.libxcb
    xorg.xcbutilwm
    mako
    libnotify
    catppuccin
    catppuccin-gtk
    home-manager
    vimix-cursors
    dconf
    dconf2nix
    glib
    obs-studio
    mpv
    rnnoise
    rnnoise-plugin
    speex
    speexdsp
    lm_sensors
    rust-analyzer
    clippy
    tree-sitter
    gcc
    rustup
    showmethekey
    smassh
    dart
    flutter
    vscode
    android-studio
    unzip
    harper
    btop
    jre8
    jdk8_headless
    libx11
    libxext
    libxrender
    libxi
    libxrandr
    libxtst
    libxcursor
    libGL
    openssl
    pkg-config
    rustup
    spotify
    sqls
    sqlite
    sql-formatter
    bun
    catnip
    quickshell
    kdePackages.qtdeclarative
    foot
    fish
    ibm-plex
    ts_query_ls
    bash-language-server
    llvmPackages_20.clang-unwrapped
    clang-tools
    lldb
    cmake-language-server
    dotnetCorePackages.sdk_8_0
    omnisharp-roslyn
    netcoredbg
    neocmakelsp
    superhtml
    vscode-langservers-extracted
    vscode-json-languageserver
    lua-language-server
    nil
    nixd
    ty
    ruff
    python313Packages.jedi
    python313Packages.jedi-language-server
    python313Packages.python-lsp-server
    vscode-css-languageserver
    yaml-language-server
    helix
    helix-gpt
    p4v
    p4d
  ];
}
